import { AuthError } from "expo-auth-session";
import { Dimensions, StyleSheet, TextInput } from "react-native";

export default StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#fff",
      alignItems: "center",
      justifyContent: "center",
      resizeMode: "cover",
    },
    container1: {
      alignItems: "center",
      justifyContent: "center",
    },
    image: {
      flex: 1,
      justifyContent: "center",
      resizeMode: "cover",
      padding: 15,
    },
    card: {
      width: Dimensions.get("window").width * 0.95,
      height: Dimensions.get("window").height * 1.01,
      alignItems: "center",
      borderRadius: 25,
    },
    button:{
      backgroundColor: "#ffffff77",
      fontSize: 20,
      padding: 15,
      width: Dimensions.get("window").width * 0.80,
      textAlign: "center",
      marginTop: 10,
      borderRadius: 10,
      color: "#DC251C",
    },
    topHeader: {
      top: 15,
      backgroundColor: "#ffffff77",
      width: Dimensions.get("window").width * 0.95,
      borderRadius: 15,
      alignItems: "center",
    },
    header: {
        height: 50,
        width: Dimensions.get("window").width * 0.98,
        justifyContent: "center",
        alignItems: "center",
        flexDirection: 'row',
        top: 15,
        zIndex: 1,
    },
    title: {
      fontSize: 40,
      textAlign: "center",
      color: "#DC251C",
      fontWeight: "bold",
    },
    logo: {
        marginTop: 5,
        width: 50,
        height: 40,
    },
    menuHeader: {
        top: -30,
        right: Dimensions.get("window").width * -0.39,
        zIndex: 1,
    },
    buttonMenu:{
        width: 40,
        height: 40,
        backgroundColor: "#ffffff77",
        fontSize: 20,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 10,
        zIndex: 1,
    },
    menuBody: {
        top: -75,
        backgroundColor: "#ffffff77",
        width: Dimensions.get("window").width * 0.90,
        alignItems: "center",
        height: 100,
        borderRadius: 10,
        paddingTop: 40,
        paddingBottom: 65,
        marginBottom: -50,
    },
    buttonLogOut:{
      backgroundColor: "#ffffff77",
      fontSize: 20,
      padding: 10,
      width: 250,
      textAlign: "center",
      marginTop: -5,
      marginBottom: 0,
      borderRadius: 10,
      color: "#DC251C",
    },
    nombreRuta: {
        fontSize: 25,
        textAlign: "center",
        color: "#000000",
        fontWeight: "bold",
    },
    body: {
        backgroundColor: "#ffffff77",
        top: Dimensions.get("window").height * 0.1,
        width: Dimensions.get("window").width * 0.95,
        alignItems: "center",
        borderRadius: 15,
        padding: 15,
        marginBottom: -15,
    },

    horariosView: {
      width: Dimensions.get("window").width * 0.92,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
    },
    horariosText: {
      fontSize: 20,
      marginBottom: 10,
      textAlign: "center",
    },
    horariosText1: {
      fontSize: 20,
      marginBottom: 10,
      textAlign: "center",
    },
    horariosSelect: {
      width: Dimensions.get("window").width * 0.46,
      flex: 1,
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      justifyContent: 'center',
    },
    horariosButton: {
      width: Dimensions.get("window").width * 0.15,
      borderWidth: 1, 
      justifyContent: "center",
      alignItems: "center",
      padding: 5,
      borderRadius: 10,
      margin: 5,
    },
});
