import { AuthError } from "expo-auth-session";
import { Dimensions, StyleSheet, TextInput } from "react-native";

export default StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#fff",
      alignItems: "center",
      justifyContent: "center",
      resizeMode: "cover",
    },
    container1: {
      alignItems: "center",
      justifyContent: "center",
    },
    image: {
      flex: 1,
      justifyContent: "center",
      resizeMode: "cover",
      padding: 15,
    },
    card: {
      width: Dimensions.get("window").width * 0.95,
      height: Dimensions.get("window").height * 1.01,
      alignItems: "center",
      borderRadius: 25,
    },
    button:{
      backgroundColor: "#ffffff77",
      fontSize: 20,
      padding: 15,
      width: Dimensions.get("window").width * 0.80,
      textAlign: "center",
      marginTop: 10,
      borderRadius: 10,
      color: "#DC251C",
    },
    topHeader: {
      top: 15,
      backgroundColor: "#ffffff77",
      width: Dimensions.get("window").width * 0.95,
      borderRadius: 15,
      alignItems: "center",
    },
    header: {
        height: 50,
        width: Dimensions.get("window").width * 0.98,
        justifyContent: "center",
        alignItems: "center",
        flexDirection: 'column',
        top: 55,
        zIndex: 1,
    },
    title: {
      fontSize: 40,
      textAlign: "center",
      color: "#DC251C",
      fontWeight: "bold",
    },
    logo: {
        marginTop: 5,
        width: 50,
        height: 40,
    },
    menuHeader: {
        top: -30,
        right: Dimensions.get("window").width * -0.39,
        zIndex: 1,
    },
    buttonMenu:{
        width: 40,
        height: 40,
        backgroundColor: "#ffffff77",
        fontSize: 20,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 10,
        zIndex: 1,
    },
    menuBody: {
        top: -50,
        width: Dimensions.get("window").width * 0.90,
        alignItems: "center",
        height: 200,
        borderRadius: 10,
        paddingTop: 40,
        paddingBottom: 65,
        marginBottom: -50,
    },
    buttonLogOut:{
      backgroundColor: "#ffffff77",
      fontSize: 20,
      padding: 10,
      width: 250,
      textAlign: "center",
      marginTop: 5,
      borderRadius: 10,
      color: "#DC251C",
    },
    nombreRuta: {
        top: 25,
        backgroundColor: "#ffffff77",
        paddingHorizontal: 10, 
        paddingVertical: 5,
        fontSize: 25,
        textAlign: "center",
        color: "#000000",
        fontWeight: "bold",
        borderRadius: 10,
        width: Dimensions.get("window").width * 0.95,
        borderBottomLeftRadius: 0,
        borderBottomRightRadius: 0,
    },
    body: {
        top: 25,
        height: Dimensions.get("window").height * 0.875,
        width: Dimensions.get("window").width * 0.95,
        borderRadius: 20, 
        borderTopLeftRadius: 0,
        borderTopRightRadius: 0,
    },
    map: {
        flex: 1,
        justifyContent: "center",
        resizeMode: "cover",
        overflow: "hidden",
        borderRadius: 20, 
        borderTopLeftRadius: 0,
        borderTopRightRadius: 0,
    },
});